### PR TITLE
fixed inline and dry violations

### LINKED ISSUE #316: Suggesting refactor of board and cell components along with removing inline tailwind classes
Description:
The vsPlayer and vsComputer components each contain their own board and cell components, but both sets are functionally identical and share the same logic.
Issue:
This setup violates the DRY (Don't Repeat Yourself) principle, as the same components are duplicated across both files.
Proposed Fix:
Refactor the shared board and cell logic into reusable models and place them in a dedicated models folder. This will eliminate redundancy, improve code organization, and ensure better maintainability across components.

### PR DESCRIPTION
**Pull request by gnaneshreddyy**
## Description
This PR refactors the vsPlayer and vsComputer components by extracting their shared Board and Cell logic into reusable models housed in models directory. Both components previously maintained duplicate implementations of these elements, leading to unnecessary redundancy and increased maintenance overhead.

this PR addresses the excessive use of inline Tailwind CSS utility classes within these components. The visual clutter and difficulty in maintaining consistent design . This improves readability, promotes design consistency, and aligns with best practices for scalable styling.
### Purpose of this PR:
Eliminate duplication: Centralize shared board and cell logic to ensure DRY principles and reduce future maintenance effort.
Enhance styling maintainability: Replace inline Tailwind classes with structured component-based styling to reduce visual bloat and enforce design consistency.
### How to test this PR manually:
Head over to player vsplayer and computer vsplayer where u can play games to test if the board is working all fine or if there are any issues in board being rendered ..if the board doesn't appear glitchy and if u see no issues in board being rendered then we can say that this refactor did not does not add any ambiguity to the main
### Related Issue
Closes #316 

## Category (replace the empty space inside brackets with x for tick)
- [ ] Bug
- [x] Refactor
- [ ] Enhancement/New Feature
- [ ] Tests
- [ ] Documentation

## Checklist 
- [x] I have read and reviewed each line of my Git/File Differences for this PR very carefully and I clearly understand the reason behind the code changes and decisions I have made
- [x] This PR is short and cant be decomposed further without breaking consistency (check ../docs/SHORT_PR.md for more information)
- [x] I have manually tested all the changes and indirect impacts these changes could have made
- [ ] I have added/updated automated testing scripts (check ../docs/TESTS_FOR_PR.md for more information)
- [x] I will keep my branch updated with main till this branch doesn't get merged
- [x] Documentations updated if applicable
- [ ] Code reviewed for accessibility
- [x] I will check the review made by coderabbit (both actionable and nitpick) and will respond with atleast a short comment of why I disagree with it
- [x] I understand maintainers might not be able to help with general doubts like git, tech stack etc
- [x] I will post the doubts regarding repository/project in Discussions tab only, so that fellow contributors could help me
- [x] I understand that doubts related to an issue or PR will be made as comment to the same.
- [ ] I do not have any existing open PR pending to be merged
- [x] If I am making this PR as a part of any competition then I will name it and mention e-mail id registered with that competition

I am making this pr as a part of competition for Hacktober fest and my registered mail id for it is :
[gnaneshreddyy@gmail.com](mailto:gnaneshreddyy@gmail.com)

## Summary by CodeRabbit

* **Refactor**
  * UI components reorganized into a shared component structure for better modularity and maintainability.
* **New Features**
  * Boards now use a responsive, square grid layout that adapts to board size.
  * Individual cells use a unified button component and a dedicated value display, improving styling and interaction consistency.
  * Single-board container supports reduced opacity for "inactive" boards.

### CODE REVIEW

File: src/components/ui/Board/Board.tsx [hunk 1]
```diff
@@ -1,5 +1,7 @@
-import clsx from "clsx";
-import Cell from "@/app/vsComputer/Cell";
+"use client";
```
Comment (Rakshitg600) [inline src/components/ui/Board/Board.tsx]: why "use client"

Comment (gnaneshreddyy) [reply src/components/ui/Board/Board.tsx]: the cell component was using it ..so i did the same here ..
now that i realized it is not required

Comment (gnaneshreddyy) [reply src/components/ui/Board/Board.tsx]: my bad small mistake as i was copying from the earlier pr

File: src/components/ui/Cell/Cell.tsx [hunk 2]
```diff
@@ -0,0 +1,23 @@
+"use client";
```
Comment (Rakshitg600) [inline src/components/ui/Cell/Cell.tsx:1]: why use client explicitly here?

**Review by Rakshitg600 — APPROVED** [review]

File: src/components/ui/Cell/Cell.tsx (hunk 2 above)
Comment (gnaneshreddyy) [reply src/components/ui/Cell/Cell.tsx:1]: the cell components has the onclick function that which takes input from user ...because of this it needs to be rendered on the client side

**Review by AshmitSherigar — APPROVED** [review]
Looks fine !
