### PR TITLE
Optimized toast cooldown logic 

### LINKED ISSUE #228: Optimize toast cooldown logic
When triggering the same toast repeatedly, there is a short delay before a new toast appears, even after the cooldown ends. This delay seems to be partially caused by React-Toastify’s internal animations and rendering process.

The fix focuses on optimizing the cooldown logic to minimize any extra delay caused by cooldown handling itself.

Steps to Reproduce:
Trigger a toast (e.g., the "Please sign in!" toast).
Wait until the cooldown is almost finished.
Trigger the same toast again very quickly or repeatedly.
Observe that the toast does not appear immediately after the previous one disappears — there is a small delay.

### PR DESCRIPTION
**Pull request by Tanishka-lab**
This PR refines the useToastCooldown hook to ensure faster re-triggering of toasts after the cooldown ends.
It doesn’t modify React-Toastify’s internal animation delays but removes any unnecessary delay caused by the cooldown logic itself.
Changes made:
Added a small early reset (cooldown - 50ms) to make cooldown end slightly earlier.
Ensured cooldown cleanup and reset logic works reliably.
Prevents duplicate toasts without introducing visual delay.
Note:
Any remaining short delay is due to React-Toastify’s animation and rendering, which is outside this hook’s control.

## Summary by CodeRabbit

* **Refactor**
  * Improved internal timer management and cleanup logic for notification cooldown handling.

### CODE REVIEW

**Comment by AshmitSherigar** [comment]
@Tanishka-lab could you pleasse look in coderabbit suggestions and nitpick comments (not compulsory to implement)

**Comment by AshmitSherigar** [comment]
@Tanishka-lab The build is failing because the code isn’t formatted according to Biome’s style rules
try running
`pnpm exec biome format .`

**Comment by Tanishka-lab** [comment]
> @Tanishka-lab could you pleasse look in coderabbit suggestions and nitpick comments (not compulsory to implement)

So I have fixed the CodeRabbit comment by making the 400ms to a file-level constant EARLY_RESET_MS. This avoids recreating the value on every callback call.

**Review by Rakshitg600 — CHANGES_REQUESTED** [review]
did you test it locally? its not working in the preview. the delay is still very noticable

**Comment by Tanishka-lab** [comment]
> did you test it locally? its not working in the preview. the delay is still very noticable

I have made some changes in the hook useToastCooldown ,it only prevents multiple toasts from being triggered too quickly and it does not add any visible delay to the toast itself but I think the delay observed is due to React-Toastify's internal processing and animation, which is outside the control of this hook

**Comment by AshmitSherigar** [comment]
> > did you test it locally? its not working in the preview. the delay is still very noticable
> 
> I have made some changes in the hook useToastCooldown ,it only prevents multiple toasts from being triggered too quickly and it does not add any visible delay to the toast itself but I think the delay observed is due to React-Toastify's internal processing and animation, which is outside the control of this hook

@Tanishka-lab then it would be better for you to change the issue description and clearly mention what you are trying to solve since it would cause a lot of confusion while testing it out and also for the purpose of understanding the PR

**Comment by Tanishka-lab** [comment]
> > did you test it locally? its not working in the preview. the delay is still very noticable
> 
> I have made some changes in the hook useToastCooldown ,it only prevents multiple toasts from being triggered too quickly and it does not add any visible delay to the toast itself but I think the delay observed is due to React-Toastify's internal processing and animation, which is outside the control of this hook

Let me know if this explanation makes sense or if I should clarify it further.

**Comment by Rakshitg600** [comment]
> > did you test it locally? its not working in the preview. the delay is still very noticable
> 
> I have made some changes in the hook useToastCooldown ,it only prevents multiple toasts from being triggered too quickly and it does not add any visible delay to the toast itself but I think the delay observed is due to React-Toastify's internal processing and animation, which is outside the control of this hook

I am a little confused, You were assigned the task that delay between two toasts should not be there. does this PR implement it or not? 
If you are trying to say that achieving this is impossible and not a limitation of your implementation, can you share some reference please?

**Comment by Rakshitg600** [comment]
> > > did you test it locally? its not working in the preview. the delay is still very noticable
> > 
> > 
> > I have made some changes in the hook useToastCooldown ,it only prevents multiple toasts from being triggered too quickly and it does not add any visible delay to the toast itself but I think the delay observed is due to React-Toastify's internal processing and animation, which is outside the control of this hook
> 
> I am a little confused, You were assigned the task that delay between two toasts should not be there. does this PR implement it or not? If you are trying to say that achieving this is impossible and not a limitation of your implementation, can you share some reference please?

My apologies, I looked at it again and realized that the delay really might not be in our control.  Just update the PR and issue description as asked by Ashmit too.

**Comment by Tanishka-lab** [comment]
@AshmitSherigar @Rakshitg600  I’ve updated the PR and issue descriptions

**Comment by AshmitSherigar** [comment]
> @AshmitSherigar @Rakshitg600 I’ve updated the PR and issue descriptions

so you are trying to solve the delay between two toasts right ?

**Comment by Tanishka-lab** [comment]
> > @AshmitSherigar @Rakshitg600 I’ve updated the PR and issue descriptions
> 
> so you are trying to solve the delay between two toasts right ?

Yes I am trying to optimize the delay.

File: src/components/hooks/useToastCooldown.ts [hunk 1]
```diff
@@ -10,14 +10,21 @@ export function useToastCooldown(cooldown: number = TOAST_DURATION) {
...
 
-		if (cooldownTimer.current) clearTimeout(cooldownTimer.current);
+		if (cooldownTimer.current) {
+			clearTimeout(cooldownTimer.current);
+		}
+		const resetTime = Math.max(0, cooldown - 50);
 		cooldownTimer.current = setTimeout(() => {
 			isOnCooldown.current = false;
-		}, cooldown);
+			cooldownTimer.current = null;
```
Comment (Rakshitg600) [inline src/components/hooks/useToastCooldown.ts:18]: what does this do?
`cooldownTimer.current = null;`

**Comment by Rakshitg600** [comment]
early reset might create confusion for other contributors. Maybe we should remove that.

**Comment by Rakshitg600** [comment]
This repository is scheduled to be migrated to @notakto [(github.com/notakto)](url) on 2 November 2025.
Please note that you may need to re-clone the repository after the transfer.

**Comment by Tanishka-lab** [comment]
> early reset might create confusion for other contributors. Maybe we should remove that.

ok so I have removed the early reset logic (resetTime) and now the cooldown resets strictly after the full duration.

File: src/components/hooks/useToastCooldown.ts (hunk 1 above)
Comment (Tanishka-lab) [reply src/components/hooks/useToastCooldown.ts:18]: It clears the reference to the old timer after the cooldown finishes. This helps prevent unexpected behavior if a new toast is triggered later.. basically, it makes sure no old timers are left running in the background.

**Review by Rakshitg600 — APPROVED** [review]
