### PR TITLE
[Fix] Sound Toggle Issue

### LINKED ISSUE #74: [Bug] Sound toggle button not working as expected
###  Bug: Sound toggle button not working as expected

**Description:**  
The **Sound** button in the in-game menu does not properly toggle game sounds. Clicking the button updates the label (`Sound: On` / `Sound: Off`), but the actual game sounds do not always follow the toggle state.

---

**Steps to Reproduce:**
1. Start a new game.  
2. Open the **Settings** menu.  
3. Toggle the **Sound** button to "On".  

---

**Expected Behavior:**  
- When sound is set to **Off**, no sounds should play.  
- When sound is set to **On**,  sounds should play normally.  

---

**Actual Behavior:**  
- Sounds doesnt play even when the button shows **Sound: On**.  

---

### PR DESCRIPTION
**Pull request by AshmitSherigar**
This PR fixes the sound issue by placing a `musicprovider `in the `layout.tsx`

closes #74 

## Summary by CodeRabbit

- New Features
  - Added a global background music provider to manage playback and mute state across the app.
- Refactor
  - Consolidated music initialization and mute handling into a single top-level provider, removing duplicate runtime hooks.
- Performance/Stability
  - More reliable audio behavior with reduced edge-case glitches and cleaner lifecycle handling.
- User Experience
  - No visual changes; background audio and mute behavior are now more consistent across pages.

### CODE REVIEW

**Comment by AshmitSherigar** [comment]
nice to add code rabbit also

**Comment by Rakshitg600** [comment]
yeah, coderabbit is right, we should remove unwanted comments and add a cleanup

**Comment by AshmitSherigar** [comment]
> yeah, coderabbit is right, we should remove unwanted comments and add a cleanup

ok will do it

File: src/app/page.tsx [hunk 1]
```diff
@@ -27,18 +27,18 @@ export default function Home() {
...
   const showTut = useTut((state) => state.showTut);
 
-  // Init music
-  useEffect(() => {
-    initBackgroundMusic(mute);
-    return () => {
-      stopBackgroundMusic();
-    };
-  }, []);
+  // // Init music
```
Comment (Rakshitg600) [inline src/app/page.tsx]: why did you not remove these comments

Comment (AshmitSherigar) [reply src/app/page.tsx]: oh u meant these ones oops

**Review by Rakshitg600 — APPROVED** [review]

**Comment by AshmitSherigar** [comment]
Please add tags bro

**Comment by Rakshitg600** [comment]
> Please add tags bro

Sorry @AshmitSherigar I don't know how I missed it.

**Comment by Rakshitg600** [comment]
Thanks for informing.
